Repository FBU2018-L3/1-Up, pull requests merged in 2018-07, with the labels that each got.

#15 Sprint 1 home screen
  One-Up/app/build.gradle
  One-Up/app/src/main/java/com/l3/one_up/HomeFragment.java
  One-Up/app/src/main/java/com/l3/one_up/MainActivity.java
  One-Up/app/src/main/res/layout/activity_main.xml
  One-Up/app/src/main/res/layout/fragment_home.xml
  One-Up/app/src/main/res/layout/item_category.xml
  One-Up/app/src/main/res/values/arrays.xml
  One-Up/app/src/main/res/values/strings.xml
Labels: enhancement, sprint1

#16 sprint1 Activity Selector
  One-Up/app/build.gradle
  One-Up/app/src/main/AndroidManifest.xml
  One-Up/app/src/main/java/com/l3/one_up/ActivityItemAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/ActivitySelectionFragment.java
  One-Up/app/src/main/java/com/l3/one_up/MainActivity.java
  One-Up/app/src/main/res/layout/activity_main.xml
  One-Up/app/src/main/res/layout/fragment_activity_selection.xml
  One-Up/app/src/main/res/layout/item_activity.xml
  One-Up/app/src/main/res/values/strings.xml
  README.md
Labels: enhancement, sprint1

#19 Sprint1 input confirmation of activities
  One-Up/app/build.gradle
  One-Up/app/src/main/java/com/l3/one_up/LoginActivity.java
  One-Up/app/src/main/java/com/l3/one_up/MainActivity.java
  One-Up/app/src/main/java/com/l3/one_up/animations/ProgressBarAnimation.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputConfirmationFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputFragment.java
  One-Up/app/src/main/java/com/l3/one_up/model/Activity.java
  One-Up/app/src/main/res/layout/input_confirmation_fragment.xml
  One-Up/app/src/main/res/layout/input_fragment.xml
  One-Up/app/src/main/res/layout/spinner_item.xml
  One-Up/app/src/main/res/values/strings.xml
Labels: sprint1

#33 Event submitted to the database
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputFragment.java
Labels: sprint2

#34 Sprint 2 - profile and navigation
  One-Up/app/build.gradle
  One-Up/app/src/main/AndroidManifest.xml
  One-Up/app/src/main/java/com/l3/one_up/HomeFragment.java
  One-Up/app/src/main/java/com/l3/one_up/MainActivity.java
  One-Up/app/src/main/java/com/l3/one_up/ProfileActivity.java
  One-Up/app/src/main/java/com/l3/one_up/ProfileFragment.java
  One-Up/app/src/main/res/layout/activity_profile.xml
  One-Up/app/src/main/res/layout/fragment_profile.xml
  One-Up/app/src/main/res/menu/menu_bottom_navigation.xml
  One-Up/app/src/main/res/values/strings.xml
Labels: Profile screen, sprint2

#35 Sprint2 feed creation
  One-Up/app/src/main/java/com/l3/one_up/ActivitySelectionFragment.java
  One-Up/app/src/main/java/com/l3/one_up/model/Activity.java
  One-Up/app/src/main/res/drawable/search_icon.png
  One-Up/app/src/main/res/layout/fragment_activity_selection.xml
  One-Up/app/src/main/res/menu/search_bar_activity.xml
  One-Up/app/src/main/res/values/colors.xml
  One-Up/app/src/main/res/values/strings.xml
  README.md
Labels: enhancement, sprint2

#38 Sprint2 parse user model
  One-Up/app/src/main/java/com/l3/one_up/ParseApplication.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputConfirmationFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/SleepFragment.java
  One-Up/app/src/main/java/com/l3/one_up/model/User.java
  One-Up/app/src/main/res/layout/fragment_input.xml
  One-Up/app/src/main/res/layout/fragment_input_confirmation.xml
Labels: sprint2

#39 Sprint 2 Actual Feed Creation
  One-Up/app/src/main/java/com/l3/one_up/adapters/ActivityItemAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/adapters/FeedItemAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/FeedFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/ProfileFragment.java
  One-Up/app/src/main/java/com/l3/one_up/model/Event.java
  One-Up/app/src/main/java/com/l3/one_up/model/ParseRelativeDate.java
  One-Up/app/src/main/res/layout/fragment_feed.xml
  One-Up/app/src/main/res/layout/item_event.xml
Labels: enhancement, sprint2

#42 Sprint 2 home screen UI improvements
  .DS_Store
  One-Up/app/src/main/java/com/l3/one_up/adapters/CategoryAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/HomeFragment.java
  One-Up/app/src/main/res/drawable/fitness.png
  One-Up/app/src/main/res/drawable/food.png
  One-Up/app/src/main/res/drawable/indoor.png
  One-Up/app/src/main/res/drawable/outdoor.png
  One-Up/app/src/main/res/layout/fragment_home.xml
  One-Up/app/src/main/res/layout/fragment_sleep.xml
  One-Up/app/src/main/res/layout/item_category.xml
  One-Up/app/src/main/res/values/arrays.xml
  One-Up/app/src/main/res/values/strings.xml
Labels: sprint2

#58 Sprint3 is private
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputFragment.java
  One-Up/app/src/main/java/com/l3/one_up/model/Event.java
  One-Up/app/src/main/res/layout/fragment_input.xml
  One-Up/app/src/main/res/values/strings.xml
Labels: sprint3

#61 Sprint3 bugs
  One-Up/app/src/main/java/com/l3/one_up/LoginActivity.java
  One-Up/app/src/main/java/com/l3/one_up/MainActivity.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/ActivitySelectionFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/HomeFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/SleepFragment.java
  One-Up/app/src/main/java/com/l3/one_up/interfaces/BackIsClickable.java
Labels: sprint3

#63 Sprint 3 stats page
  One-Up/app/build.gradle
  One-Up/app/src/main/java/com/l3/one_up/MainActivity.java
  One-Up/app/src/main/java/com/l3/one_up/Objective.java
  One-Up/app/src/main/java/com/l3/one_up/ParseApplication.java
  One-Up/app/src/main/java/com/l3/one_up/ProfileActivity.java
  One-Up/app/src/main/java/com/l3/one_up/adapters/ActivityItemAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/adapters/CategoryAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/adapters/GoalItemAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/ActivitySelectionFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/CategorySelectionFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/FeedFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/GoalSummaryFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/HomeFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputConfirmationFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/StatsFragment.java
  One-Up/app/src/main/java/com/l3/one_up/model/Goal.java
  One-Up/app/src/main/res/layout/fragment_category_selection.xml
  One-Up/app/src/main/res/layout/fragment_goal_summary.xml
  One-Up/app/src/main/res/layout/fragment_home.xml
  One-Up/app/src/main/res/layout/fragment_stats.xml
  One-Up/app/src/main/res/layout/item_goal.xml
Labels: enhancement, sprint3

#65 Sprint3 facebook login
  One-Up/app/build.gradle
  One-Up/app/src/main/AndroidManifest.xml
  One-Up/app/src/main/java/com/l3/one_up/DeepLinkingActivity.java
  One-Up/app/src/main/java/com/l3/one_up/ParseApplication.java
  One-Up/app/src/main/java/com/l3/one_up/ProfileActivity.java
  One-Up/app/src/main/java/com/l3/one_up/adapters/FriendsAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/ActivitySelectionFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/FriendsFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/ProfileFragment.java
  One-Up/app/src/main/java/com/l3/one_up/interfaces/FacebookCallComplete.java
  One-Up/app/src/main/java/com/l3/one_up/model/FacebookQuery.java
  One-Up/app/src/main/java/com/l3/one_up/model/GlideAppModule.java
  One-Up/app/src/main/java/com/l3/one_up/model/OrderFacebookUsersById.java
  One-Up/app/src/main/java/com/l3/one_up/model/OrderParseUsersByFbId.java
  One-Up/app/src/main/java/com/l3/one_up/model/User.java
  One-Up/app/src/main/res/drawable/image1.png
  One-Up/app/src/main/res/layout/activity_deep_linking.xml
  One-Up/app/src/main/res/layout/fragment_friends.xml
  One-Up/app/src/main/res/layout/fragment_profile.xml
  One-Up/app/src/main/res/layout/item_friend.xml
  One-Up/app/src/main/res/menu/menu_bottom_navigation.xml
  One-Up/app/src/main/res/values/strings.xml
Labels: enhancement, sprint3

#66 Facebook Friend Crash fix
  One-Up/app/src/main/java/com/l3/one_up/fragments/FriendsFragment.java
  One-Up/app/src/main/java/com/l3/one_up/interfaces/FacebookCallComplete.java
  One-Up/app/src/main/res/layout/fragment_friends.xml
Labels: refinements, sprint3

#69 When the user goes to sleep, the device receives the notification
  One-Up/app/src/main/AndroidManifest.xml
  One-Up/app/src/main/java/com/l3/one_up/LoginActivity.java
  One-Up/app/src/main/java/com/l3/one_up/MainActivity.java
  One-Up/app/src/main/java/com/l3/one_up/ParseApplication.java
Labels: enhancement, sprint3

#70 Sprint 3 - count goals
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputFragment.java
  One-Up/app/src/main/java/com/l3/one_up/model/Goal.java
Labels: sprint3

#71 Sprint3 friend feed
  One-Up/app/src/main/java/com/l3/one_up/adapters/FeedItemAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/FriendsFragment.java
  One-Up/app/src/main/java/com/l3/one_up/interfaces/FacebookCallComplete.java
  One-Up/app/src/main/res/layout/fragment_feed.xml
  One-Up/app/src/main/res/layout/fragment_friends.xml
Labels: enhancement, sprint3

#79 Sprint 4 goal refinements
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputFragment.java
  One-Up/app/src/main/res/layout/fragment_input.xml
  One-Up/app/src/main/res/values/strings.xml
Labels: refinements, sprint4

#78 Sprint 4 calendar view
  One-Up/app/src/main/java/com/l3/one_up/ProfileActivity.java
  One-Up/app/src/main/java/com/l3/one_up/adapters/FeedItemAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/CalendarFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/FeedFragment.java
  One-Up/app/src/main/java/com/l3/one_up/model/Event.java
  One-Up/app/src/main/res/layout/fragment_calendar.xml
  One-Up/app/src/main/res/values/strings.xml
Labels: sprint4

#82 Sprint 4 goal modal 2nd try
  One-Up/app/src/main/java/com/l3/one_up/GoalCompletedFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputFragment.java
  One-Up/app/src/main/res/layout/fragment_goal_completed.xml
Labels: sprint3

#84 Sprint4 push notifications
  One-Up/app/build.gradle
  One-Up/app/src/main/java/com/l3/one_up/ParseApplication.java
  One-Up/app/src/main/java/com/l3/one_up/model/Event.java
Labels: bug, sprint4
