Repository FBU2018-L3/1-Up, pull requests merged in 2018-08, with the labels that each got.

#86 Sprint4 search friends
  One-Up/app/src/main/java/com/l3/one_up/adapters/FriendsAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/ActivitySelectionFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/FriendsFragment.java
  One-Up/app/src/main/java/com/l3/one_up/model/FacebookQuery.java
  One-Up/app/src/main/res/layout/item_friend.xml
Labels: enhancement, sprint4

#88 Sprint 4 - Share FB post on activity input
  One-Up/app/build.gradle
  One-Up/app/src/main/AndroidManifest.xml
  One-Up/app/src/main/java/com/l3/one_up/fragments/HomeFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputConfirmationFragment.java
  One-Up/app/src/main/res/layout/fragment_home.xml
  One-Up/app/src/main/res/layout/fragment_input_confirmation.xml
  One-Up/app/src/main/res/values/colors.xml
  One-Up/app/src/main/res/values/strings.xml
  One-Up/build.gradle
Labels: enhancement, sprint4

#89 Corrected the initialization of the event object
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputFragment.java
  One-Up/app/src/main/java/com/l3/one_up/model/Event.java
Labels: bug, sprint4

#90 Sprint 4 - share completed goals
  One-Up/app/src/main/java/com/l3/one_up/fragments/GoalCompletedFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputFragment.java
  One-Up/app/src/main/res/layout/fragment_goal_completed.xml
Labels: sprint4

#97 Sprint 4 existing goal alert bug
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputFragment.java
Labels: bug, sprint4

#100 Sprint 4 change default font
  One-Up/app/src/main/assets/fonts/DisposableDroidBB.ttf
  One-Up/app/src/main/assets/fonts/DisposableDroidBB_bld.ttf
  One-Up/app/src/main/assets/fonts/DisposableDroidBB_bldital.ttf
  One-Up/app/src/main/assets/fonts/DisposableDroidBB_ital.ttf
  One-Up/app/src/main/java/com/l3/one_up/ParseApplication.java
  One-Up/app/src/main/java/com/l3/one_up/services/TypefaceUtil.java
  One-Up/app/src/main/res/values/styles.xml
Labels: refinements, sprint4

#101 Sprint4 change design of timeline
  .DS_Store
  One-Up/app/src/main/java/com/l3/one_up/ProfileActivity.java
  One-Up/app/src/main/java/com/l3/one_up/adapters/FeedItemAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/ActivitySelectionFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/FeedFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/FriendsFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputConfirmationFragment.java
  One-Up/app/src/main/res/drawable/andy_celebrating.gif
  One-Up/app/src/main/res/layout/activity_profile.xml
  One-Up/app/src/main/res/layout/fragment_activity_selection.xml
  One-Up/app/src/main/res/layout/fragment_feed.xml
  One-Up/app/src/main/res/layout/fragment_friends.xml
  One-Up/app/src/main/res/layout/item_event.xml
  One-Up/app/src/main/res/values/strings.xml
Labels: refinements, sprint4

#103 sprint 4 - prevent app crash on empty friends response
  One-Up/app/src/main/java/com/l3/one_up/fragments/FriendsFragment.java
  One-Up/app/src/main/java/com/l3/one_up/model/FacebookQuery.java
Labels: bug, sprint4

#104 sprint4 - refactor file system
  One-Up/app/src/main/AndroidManifest.xml
  One-Up/app/src/main/java/com/l3/one_up/MainActivity.java
  One-Up/app/src/main/java/com/l3/one_up/adapters/FeedItemAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/adapters/FriendsAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/ActivitySelectionFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/FriendsFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/ProfileFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/StatsFragment.java
  One-Up/app/src/main/java/com/l3/one_up/model/GlideAppModule.java
  One-Up/app/src/main/java/com/l3/one_up/model/Objective.java
  One-Up/app/src/main/java/com/l3/one_up/services/DeepLinkingActivity.java
  One-Up/app/src/main/java/com/l3/one_up/services/MyAppGlideModule.java
  One-Up/app/src/main/java/com/l3/one_up/services/OrderFacebookUsersById.java
  One-Up/app/src/main/java/com/l3/one_up/services/OrderParseUsersByFbId.java
  One-Up/app/src/main/java/com/l3/one_up/services/ParseRelativeDate.java
  One-Up/app/src/main/res/layout/activity_deep_linking.xml
Labels: refinements, sprint4

#105 Sprint4 ui things
  One-Up/app/src/main/res/drawable/bow.png
  One-Up/app/src/main/res/drawable/coin.png
  One-Up/app/src/main/res/drawable/danger.jpg
  One-Up/app/src/main/res/drawable/dangerbottom.jpg
  One-Up/app/src/main/res/drawable/dangertop.jpeg
  One-Up/app/src/main/res/drawable/facebookbackground.jpg
  One-Up/app/src/main/res/drawable/gemblue.png
  One-Up/app/src/main/res/drawable/gemgreen.png
  One-Up/app/src/main/res/drawable/gemred.png
  One-Up/app/src/main/res/drawable/heart.png
  One-Up/app/src/main/res/drawable/indoor.png
  One-Up/app/src/main/res/drawable/potionblue.png
  One-Up/app/src/main/res/drawable/swordwood.png
  One-Up/app/src/main/res/drawable/tome.png
  One-Up/app/src/main/res/drawable/upg_shield.png
  One-Up/app/src/main/res/layout/activity_deep_linking.xml
  One-Up/app/src/main/res/layout/item_category.xml
Labels: refinements, sprint4

#107 Sprint5 changing categories images
  .DS_Store
  One-Up/app/src/main/res/drawable/fitness.png
  One-Up/app/src/main/res/drawable/food.png
  One-Up/app/src/main/res/drawable/indoor.png
  One-Up/app/src/main/res/drawable/outdoor.png
  One-Up/app/src/main/res/values/arrays.xml
Labels: refinements, sprint5

#115 Sprint5 design
  .DS_Store
  One-Up/app/build.gradle
  One-Up/app/src/main/java/com/l3/one_up/adapters/FeedItemAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/adapters/PowerUpAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/FeedFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/FriendsFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/GoalSummaryFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/HomeFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/SleepFragment.java
  One-Up/app/src/main/java/com/l3/one_up/model/FacebookQuery.java
  One-Up/app/src/main/res/drawable/cool.png
  One-Up/app/src/main/res/drawable/dog.png
  One-Up/app/src/main/res/drawable/facebook.png
  One-Up/app/src/main/res/drawable/fitness.png
  One-Up/app/src/main/res/drawable/food.png
  One-Up/app/src/main/res/drawable/indoor.png
  One-Up/app/src/main/res/drawable/logout.png
  One-Up/app/src/main/res/drawable/mario_android.png
  One-Up/app/src/main/res/drawable/menu_icon_calendar.png
  One-Up/app/src/main/res/drawable/menu_icon_friends.png
  One-Up/app/src/main/res/drawable/menu_icon_goals.png
  One-Up/app/src/main/res/drawable/menu_icon_profile.png
  One-Up/app/src/main/res/drawable/menu_icon_stats.png
  One-Up/app/src/main/res/drawable/moon.png
  One-Up/app/src/main/res/drawable/nyan.png
  One-Up/app/src/main/res/drawable/outdoor.png
  One-Up/app/src/main/res/drawable/power_ups.png
  One-Up/app/src/main/res/drawable/profile_img_mushroom.png
  One-Up/app/src/main/res/layout/fragment_home.xml
  One-Up/app/src/main/res/layout/fragment_profile.xml
  One-Up/app/src/main/res/layout/fragment_sleep.xml
  One-Up/app/src/main/res/layout/item_powerup.xml
  One-Up/app/src/main/res/layout/sleep_toggle.xml
  One-Up/app/src/main/res/menu/menu_bottom_navigation.xml
  One-Up/app/src/main/res/values/colors.xml
  One-Up/app/src/main/res/values/styles.xml
Labels: refinements, sprint5

#116 Sprint5 goal progress
  One-Up/app/src/main/java/com/l3/one_up/adapters/GoalItemAdapter.java
  One-Up/app/src/main/res/layout/item_goal.xml
Labels: enhancement, sprint5

#117 Sprint 5 select avatar
  One-Up/app/src/main/java/com/l3/one_up/adapters/AvatarSelectionAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/AvatarSelectionFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/GoalCompletedFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/HomeFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputConfirmationFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/ProfileFragment.java
  One-Up/app/src/main/java/com/l3/one_up/model/User.java
  One-Up/app/src/main/java/com/l3/one_up/services/AvatarFinder.java
  One-Up/app/src/main/java/com/l3/one_up/services/DeepLinkingActivity.java
  One-Up/app/src/main/res/layout/activity_deep_linking.xml
  One-Up/app/src/main/res/layout/fragment_avatar_selection.xml
  One-Up/app/src/main/res/layout/item_avatar.xml
  One-Up/app/src/main/res/values/arrays.xml
  One-Up/app/src/main/res/values/strings.xml
Labels: enhancement, sprint5

#119 The chart is fixed
  One-Up/app/src/main/java/com/l3/one_up/formatters/XAxisDateValueFormatter.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/ChartFragment.java
Labels: enhancement, sprint5

#118 Sprint5 power up bug
  One-Up/app/src/main/java/com/l3/one_up/fragments/HomeFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/PowerUpFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/ProfileFragment.java
  One-Up/app/src/main/java/com/l3/one_up/listeners/OnRedeemedPowerUpRefresh.java
Labels: bug, sprint5

#124 Sprint 5 enhancements
  One-Up/app/src/main/res/drawable/box2.png
  One-Up/app/src/main/res/drawable/bricks.png
  One-Up/app/src/main/res/drawable/horizontal.png
  One-Up/app/src/main/res/drawable/ogbox.png
  One-Up/app/src/main/res/drawable/vertical.png
  One-Up/app/src/main/res/layout/button_share_facebook.xml
  One-Up/app/src/main/res/layout/fragment_category_selection.xml
  One-Up/app/src/main/res/layout/fragment_goal_completed.xml
  One-Up/app/src/main/res/layout/fragment_home.xml
  One-Up/app/src/main/res/layout/fragment_input.xml
  One-Up/app/src/main/res/layout/fragment_input_confirmation.xml
  One-Up/app/src/main/res/layout/item_category.xml
  One-Up/app/src/main/res/layout/modal_dots.xml
  One-Up/app/src/main/res/values/colors.xml
  One-Up/app/src/main/res/values/dimensions.xml
Labels: refinements, sprint5

#126 Sprint5 ui stuff
  .DS_Store
  One-Up/app/src/main/java/com/l3/one_up/MainActivity.java
  One-Up/app/src/main/java/com/l3/one_up/ProfileActivity.java
  One-Up/app/src/main/java/com/l3/one_up/adapters/FeedItemAdapter.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/FeedFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/FriendsFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/HomeFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputConfirmationFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/PowerUpFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/ProfileFragment.java
  One-Up/app/src/main/java/com/l3/one_up/interfaces/SelectNavBarItem.java
  One-Up/app/src/main/java/com/l3/one_up/model/User.java
  One-Up/app/src/main/res/drawable/cool.png
  One-Up/app/src/main/res/drawable/moon.png
  One-Up/app/src/main/res/drawable/nyan.png
  One-Up/app/src/main/res/drawable/profile_cool.png
  One-Up/app/src/main/res/drawable/profile_dino.png
  One-Up/app/src/main/res/drawable/profile_dogge.png
  One-Up/app/src/main/res/drawable/profile_grizzly.png
  One-Up/app/src/main/res/drawable/profile_mushroom.png
  One-Up/app/src/main/res/drawable/profile_panda.png
  One-Up/app/src/main/res/drawable/profile_polar.png
  One-Up/app/src/main/res/layout/fragment_avatar_selection.xml
  One-Up/app/src/main/res/layout/fragment_home.xml
  One-Up/app/src/main/res/layout/fragment_profile.xml
  One-Up/app/src/main/res/layout/item_avatar.xml
  One-Up/app/src/main/res/layout/item_event.xml
  One-Up/app/src/main/res/layout/recyclerview_footer.xml
  One-Up/app/src/main/res/values/arrays.xml
Labels: refinements, sprint5

#128 Sprint 5 formatting fixes
  One-Up/app/src/main/java/com/l3/one_up/fragments/FeedFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/HomeFragment.java
  One-Up/app/src/main/res/layout/fragment_goal_completed.xml
  One-Up/app/src/main/res/layout/fragment_home.xml
  One-Up/app/src/main/res/layout/fragment_input_confirmation.xml
  One-Up/app/src/main/res/layout/item_goal.xml
  One-Up/app/src/main/res/layout/powerup_toggle.xml
  One-Up/app/src/main/res/layout/sleep_toggle.xml
  One-Up/app/src/main/res/values/dimensions.xml
Labels: refinements, sprint5

#130 Sprint5 luz ui things
  .DS_Store
  One-Up/app/src/main/java/com/l3/one_up/fragments/ActivitySelectionFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/GoalCompletedFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputConfirmationFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/InputFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/PowerUpFragment.java
  One-Up/app/src/main/java/com/l3/one_up/fragments/SleepFragment.java
  One-Up/app/src/main/res/layout/fragment_activity_selection.xml
  One-Up/app/src/main/res/layout/fragment_input.xml
  One-Up/app/src/main/res/layout/item_category.xml
  One-Up/app/src/main/res/values/strings.xml
  README.md
Labels: enhancement, sprint5

#131 Sprint 5 make categories modular
  .DS_Store
  One-Up/app/src/main/res/drawable/facebookbackground.jpg
  One-Up/app/src/main/res/drawable/fitness.png
  One-Up/app/src/main/res/drawable/food.png
  One-Up/app/src/main/res/drawable/indoor.png
  One-Up/app/src/main/res/drawable/outdoor.png
  One-Up/app/src/main/res/layout/category_dots.xml
  One-Up/app/src/main/res/layout/fragment_goal_completed.xml
  One-Up/app/src/main/res/layout/fragment_input.xml
  One-Up/app/src/main/res/layout/fragment_input_confirmation.xml
  One-Up/app/src/main/res/layout/fragment_send_power_up.xml
  One-Up/app/src/main/res/layout/item_category.xml
  One-Up/app/src/main/res/values/colors.xml
  One-Up/app/src/main/res/values/dimensions.xml
Labels: refinements, sprint5

#132 format friends item
  One-Up/app/src/main/res/layout/item_friend.xml
  One-Up/app/src/main/res/values/dimensions.xml
Labels: refinements, sprint5
